name: Update Parser
on:
  workflow_dispatch:

jobs:
  Deploy-Pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Deps
        run: yarn add @saber2pr/jsx-ast-parser

      - name: Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit . -m "chore: update parser"
          git push
